name: basic-check

on:
  pull_request:
    branches:
      - main

jobs:
  basic:
    name: CI Passed ✅  # <- Add this line!
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "This is a basic check that always passes."
